mcs_km: fix xenbus_driver.remove signature for kernel >= 6.3
Mainline commit 7cffcade57a4 ("xen: make remove callback of xen driver
void returned") changed xenbus_driver::remove return type from int to
void in v6.3, causing build failures on kp920 industry kernel 6.x:

  xen-mcsback.c:670:27: error: initialization of
    'void (*)(struct xenbus_device *)' from incompatible pointer type
    'int (*)(struct xenbus_device *)' [-Werror=incompatible-pointer-types]
        .remove = mcs_backend_remove,
                  ^~~~~~~~~~~~~~~~~~

Provide both signatures behind LINUX_VERSION_CODE so the module still
builds on older kernels (e.g. 5.10 LTS) while supporting 6.3+.

Closes openeuler/yocto-meta-openeuler#1348

Signed-off-by: 段廷伟 <2624934035@qq.com>